version: "3.8"

services:
  db:
    container_name: database
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - db-volume:/var/lib/postgresql/data

  backend:
    image: joniba1/backend-image  
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db

volumes:
  db-volume:
